server:
  port: 8058

spring:
  application:
    name: auth-gateway
  datasource:
    driver-class-name: org.postgresql.Driver
    password: AVNS_bmkQTY2BB21V77w1WnX
    username: doadmin
    url: jdbc:postgresql://kazgeowarning-do-user-16008876-0.c.db.ondigitalocean.com:25060/defaultdb?currentSchema=news&sslmode=require
  jmx:
    enabled: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        temp.use_jdbc_metadata_defaults: false
        synonyms: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default-schema: OSADMIN
        enable_lazy_load_no_trans: true
    show-sql: false
