server.port=8086
server.servlet.context-path=/report

database.url=jdbc:postgresql://localhost:5432/geowarning?currentSchema=public
database.login=postgres
database.password=postgres


spring.datasource.url=jdbc:postgresql://localhost:5432/geowarning?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

notification=${NOTIFICATION_URL:http://localhost:8083}
